spring:
  datasource:
    services :

      password: X400SjebphV@

    transac :

      password: X400SjebphV@

    bank1 :

      password : X400SjebphV@

    bank2 :

      password : X400SjebphV@

    activities :

      password : X400SjebphV@

  mongodb:
    clients:

      password: X400SjebphV!

    addClients:

      password: X400SjebphV!