logging:
  level:
    root: DEBUG
    sun.rmi: ERROR
    javax.management.remote.rmi: ERROR

spring:
  config:
    import: "classpath:application-password.yaml"

  datasource:
    services :
      jdbc-url : jdbc:mysql://20.197.5.60:3306/bdservices
      username : datamining
      driver-class-name: com.mysql.cj.jdbc.Driver

    transac :
      jdbc-url: jdbc:mysql://20.197.5.60:3306/bdtransac
      username: datamining
      driver-class-name: com.mysql.cj.jdbc.Driver

    bank1 :
      jdbc-url: jdbc:mysql://20.197.5.60:3306/bdbank1
      username: datamining
      driver-class-name: com.mysql.cj.jdbc.Driver

    bank2 :
      jdbc-url: jdbc:mysql://20.197.5.60:3306/bdbank2
      username: datamining
      driver-class-name: com.mysql.cj.jdbc.Driver

    activities :
      jdbc-url : jdbc:mysql://datamining.masmzi.icu:3306/bdactivites?autoReconnect=true&useSSL=false&serverTimezone=UTC
      username : datamining
      driver-class-name : com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      Clients:
        uri: mongodb+srv://userdb:X400SjebphV!@bdauth.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
  # ${mongodb.clients.password} X400SjebphV!
      addClients:
        uri: mongodb://userdb:X400kebphV%40@98.71.128.33:27017/
      #${mongodb.addClients.password}