logging:
  level:
    root: DEBUG
    sun.rmi: ERROR
    javax.management.remote.rmi: ERROR

spring:
  config:
    import: "application-password.yaml"

  datasource:
    services :
      jdbc-url : jdbc:mysql://20.197.5.60:3306/bdservices
      username : datamining
      driver-class-name: com.mysql.cj.jdbc.Driver

    transac :
      jdbc-url: jdbc:mysql://20.197.5.60:3306/bdtransac
      username: datamining
      driver-class-name: com.mysql.cj.jdbc.Driver

    bank1 :
      jdbc-url: jdbc:mysql://20.197.5.60:3306/bdbank1
      username: datamining
      driver-class-name: com.mysql.cj.jdbc.Driver

    bank2 :
      jdbc-url: jdbc:mysql://20.197.5.60:3306/bdbank2
      username: datamining
      driver-class-name: com.mysql.cj.jdbc.Driver

    activities :
      jdbc-url : jdbc:mysql://datamining.masmzi.icu:3306/bdactivites
      username : datamining
      diver-class-name : com.mysql.cj.jdbc.Driver