logging:
  level:
    root: DEBUG
    sun.rmi: ERROR
    javax.management.remote.rmi: ERROR

spring:
  config:
    import: "application-password.yaml"

  datasource:
    services :
      jdbc-url : jdbc:mysql://20.197.5.60:3306/bdservices
      username : api
      driver-class-name: com.mysql.cj.jdbc.Driver

    transac :
      jdbc-url: jdbc:mysql://20.197.5.60:3306/bdtransac
      username: api
      driver-class-name: com.mysql.cj.jdbc.Driver